//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katalog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KatalogDataModelContainer : DbContext
    {
        public KatalogDataModelContainer()
            : base("name=KatalogDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departement> DepartementSet { get; set; }
        public virtual DbSet<Sprachgruppe> SprachgruppeSet { get; set; }
        public virtual DbSet<Dorf> DorfSet { get; set; }
        public virtual DbSet<Kategorie> KategorieSet { get; set; }
        public virtual DbSet<Objekt> ObjektSet { get; set; }
    }
}
