//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objekt
    {
        public int Id { get; set; }
        public string ObjektNummer { get; set; }
        public string ObjektName { get; set; }
        public string Bilder { get; set; }
        public string Herkunft { get; set; }
        public string BeschreibungMaterial { get; set; }
        public string BeschreibungHerstellung { get; set; }
        public string Zustand { get; set; }
        public string Masse { get; set; }
        public string ErworbenBei { get; set; }
        public string Datierung { get; set; }
        public string Versicherungswert { get; set; }
    
        public virtual Dorf Dorf { get; set; }
        public virtual Kategorie Kategorie { get; set; }
    }
}
